CREATE TABLE TB_PERFUME_REVIEW_M (
    PERFUME_ID  BIGINT        NOT NULL,
    AUTHOR      VARCHAR(100),
    REVIEWS TEXT,
    -- CONSTRAINT CK_TB_PERFUME_REVIEW_LEN
    --     CHECK (char_length(REVIEWS) BETWEEN 10 AND 1000)
    WRITE_DT    TIMESTAMP     NOT NULL,
    LOAD_DT     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_PERFUME_REVIEW_M
        PRIMARY KEY (PERFUME_ID, WRITE_DT),

    CONSTRAINT FK_TB_PERFUME_REVIEW_M_PERFUME
        FOREIGN KEY (PERFUME_ID)
        REFERENCES TB_PERFUME_BASIC_M (PERFUME_ID)
);